Fix building on RISC-V (again)
Apparently, commit d7271fc identified the problem, but has not fixed it
completely, in that a couple more CPU registers from <sys/ucontext.h>
get in the way on Fedora 33/RISC-V.  Fix that.

.../regs.h:186:2: error: expected identifier before numeric constant
  186 |  REG_S1,